name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 🔥 Extract repository name for base path
      - name: Get repository name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

      # 🔥 Inject base path into HTML
      - name: Inject base path
        run: |
          echo "📦 Injecting base path: /${{ env.REPO_NAME }}/"
          sed -i 's|<head>|<head>\n    <base href="/${{ env.REPO_NAME }}/">|' index.html
          echo "✓ Base path injected successfully"
          echo ""
          echo "📄 Modified index.html (first 20 lines):"
          head -20 index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4